## need to add server.  entries to enable HTTPS with SSL keystore, replace "????" with correct entries

server.port=8443
server.ssl.key-alias=selfsignedSAN
server.ssl.key-store-password=passone
server.ssl.key-store=classpath:keystore-2.jks
server.ssl.key-store-type=JKS
 
